name: Test & Publish to PyPI

on:
  push:
    branches: [ "main" ]
    tags:
      - "v*"    # Trigger publish on tags like v0.1.0, v1.2.3, etc.
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Run Tests (Python 3.8, 3.9, 3.10, 3.11, 3.12)
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -v

      - name: Test CLI functionality
        run: |
          # Test that the CLI tool can be imported and shows help
          python -c "import github_org_stats; print('Package import successful')"
          pip install -e .
          github-org-stats --help

  test-install:
    name: Test Package Installation
    runs-on: ubuntu-latest
    needs: [test]

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Test pip install
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install .
          github-org-stats --help

      - name: Test editable install
        run: |
          pip uninstall -y github-org-stats
          pip install -e .
          github-org-stats --help

  publish:
    # Only run this job if it is a tag starting with 'v'
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [ test, test-install ]
    runs-on: ubuntu-latest
    permissions:
      # Provide the OIDC token for PyPI
      id-token: write
      # You may also need read access to the repo content if your step checks out code
      contents: read

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          # Use a single Python version for building/publishing
          python-version: "3.10"

      - name: Build package
        run: |
          python -m pip install --upgrade pip setuptools wheel build
          python -m build

      - name: Verify package contents
        run: |
          pip install twine
          twine check dist/*

      # ----- Publish via OIDC to PyPI -----
      - name: Publish via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          package-name: "github-org-stats"
        env:
          # Required to request an OIDC token from GitHub
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}